import { WorkModel } from "../components/work/WorkModel";

export const works: WorkModel[] = [
    {
        start: "2021",
        end: "2023",
        title: "Mobile Application Developer",
        company: "Boutir Ltd.",
        description:
            "I spearheaded a pivotal migration project utilizing React Native, which yielded remarkable results such as doubling our development pace and significantly reducing the need for Quality Assurance (QA) resources. This endeavor involved introducing the implementation of Appium for automated testing, a strategic move that not only streamlined our QA processes but also greatly enhanced the efficiency of our Continuous Integration and Continuous Deployment (CICD) pipelines. Furthermore, I was responsible for seamlessly integrating a live-streaming module into our application, thereby boosting user engagement and facilitating substantial revenue growth. My role also involved effective collaboration with colleagues situated across different time zones, ensuring open and productive communication, which was crucial for our cohesive teamwork.",
        techStack: [
            "Swift",
            "Kotlin",
            "React Native",
            "TypeScript",
            "Xode",
            "Android Studio",
            "Appium",
            "WebDriverIO",
            "Redux",
            "Redux Saga",
            "Jest",
            "Firebase",
            "Google Cloud Platform",
            "Google Play Store",
            "App Store Connect",
            "Fastlane",
            "Github Actions",
            "JIRA",
            "Confluence",
            "Figma",
        ],
        link: "https://www.boutir.com/",
    },
    {
        start: "JUL",
        end: "AUG 2020",
        title: "Mobile Application Developer",
        company: "WonderKin Ltd.",
        description:
            "I developed a highly user-friendly mobile application using Flutter, specifically designed to establish seamless Bluetooth Low Energy (BLE) connections with smart diapers. This innovative app streamlines the process of monitoring diaper status. It features a meticulously organized and intuitive chart-based user interface, offering users clear and insightful visual representations of various metrics such as diaper wetness, urine volume, and posture trends. This approach empowers parents and caregivers with a comprehensive and easy-to-understand overview of their baby's well-being, enhancing the overall childcare experience.",
        techStack: [
            "Flutter",
            "Dart",
            "Firebase",
            "JIRA",
            "App Store Connect",
            "Google Play Store",
            "Github",
            "Figma",
        ],
    },
    {
        start: "2018",
        end: "2019",
        title: "Junior Programmer",
        company: "AppQuick.co",
        description:
            "I have a proven track record of developing customized mobile applications for prominent corporations, aimed at optimizing event organization and elevating the attendee experience. My work includes designing and implementing a user-friendly Content Management System (CMS) that allows clients to effortlessly update and manage app data in real-time. I also prioritize close collaboration with corporate clients to tailor app functionalities to their specific event requirements, ensuring seamless alignment with their objectives and goals. This approach results in highly tailored and efficient solutions that enhance the overall event experience for both organizers and attendees.",
        techStack: [
            "Swift",
            "Xcode",
            "Firebase",
            "Kotlin",
            "AWS",
            "Android Studio",
        ],
        link: "https://www.appquick.co/",
    },
];
