import { WorkModel } from "../components/work/WorkModel";

export const works: WorkModel[] = [
    {
        start: 2021,
        end: 2023,
        title: "Mobile Application Developer",
        company: "Boutir Ltd.",
        description:
            "Developing mobile application with React Native and TypeScript.",
        techStack: [
            "React Native",
            "TypeScript",
            "Redux",
            "Redux Saga",
            "React Navigation",
            "React Native Paper",
            "React Native Testing Library",
            "Jest",
            "Detox",
            "Firebase",
            "Google Cloud Platform",
            "Google Analytics",
            "Google Tag Manager",
            "Google Play Store",
            "App Store Connect",
            "Fastlane",
            "Bitrise",
            "Github Actions",
            "Jira",
            "Confluence",
            "Notion",
            "Figma",
        ],
        link: "https://www.boutir.com/",
    },
    {
        start: 2020,
        end: 2020,
        title: "Mobile Application Developer",
        company: "WonderKin Ltd.",
        description:
            "Developing mobile application with React Native and TypeScript.",
        techStack: [
            "React Native",
            "TypeScript",
            "Redux",
            "Redux Saga",
            "React Navigation",
            "React Native Paper",
            "React Native Testing Library",
            "Jest",
            "Detox",
            "Firebase",
            "Google Cloud Platform",
            "Google Analytics",
            "Google Tag Manager",
            "Google Play Store",
            "App Store Connect",
            "Fastlane",
            "Bitrise",
            "Github Actions",
            "Jira",
            "Confluence",
            "Notion",
            "Figma",
        ],
    },
    {
        start: 2017,
        end: 2019,
        title: "Junior Programmer",
        company: "AppQuick.co",
        description: "Developing mobile application with React Native.",
        techStack: ["React Native", "Redux", "Redux Saga", "React Navigation"],
        link: "https://www.appquick.co/",
    },
];
